# Generated by Django 5.0.7 on 2024-09-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        # このマイグレーションは空のマイグレーションです
        # 既存のモデルに変更がないため、何も実行しません
    ]
