# Generated by Django 5.2.6 on 2025-09-14 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="judgment",
            field=models.CharField(
                choices=[("APPROVED", "承認"), ("REJECTED", "却下")],
                default="APPROVED",
                help_text="判定結果",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="judgment",
            name="rejection_reason",
            field=models.CharField(blank=True, help_text="却下理由", max_length=200),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="speed_kmh",
            field=models.FloatField(
                blank=True,
                help_text="速度 (km/h)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
