# Generated by Django 5.2.6 on 2025-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0003_judgment_judgment_judgment_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_rejected",
            field=models.BooleanField(default=False, help_text="却下されたかどうか"),
        ),
    ]
