# Generated by Django 5.2.6 on 2025-09-14 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0005_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="description",
            field=models.TextField(blank=True, help_text="投稿の説明文", max_length=500),
        ),
    ]
