# Generated by Django 5.2.6 on 2025-09-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_submission_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("USER", "一般ユーザー"), ("JUDGE", "判定者"), ("ADMIN", "管理者")],
                default="USER",
                help_text="ユーザー権限",
                max_length=10,
            ),
        ),
    ]
