# Generated by Django 5.2.6 on 2025-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image_base64",
            field=models.TextField(
                blank=True, help_text="Base64エンコードされたプロフィール画像", null=True
            ),
        ),
    ]
