# Generated by Django 5.2.6 on 2025-09-21 01:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0008_userprofile_profile_image_base64"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image_base64",
        ),
    ]
