# Generated by Django 5.2.6 on 2024-09-27 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_auto_20240927_0600'),
        ('submissions', '0009_remove_userprofile_profile_image_base64'),
    ]

    operations = [
        # マージ用マイグレーション - 依存関係を一本化するだけ
    ]
